"""empty message

Revision ID: 59b510bb7dd2
Revises: 53cd9ae94628
Create Date: 2022-07-06 22:59:35.286450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b510bb7dd2'
down_revision = '53cd9ae94628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('book', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('book', 'title')
    # ### end Alembic commands ###
